
DROP TABLE IF EXISTS residential_building;
-- Create a table residential_building data table
CREATE TABLE residential_building
    (Major CHAR (6)
    ,Minor CHAR (4)
    ,BuildingNmbr NUMERIC (3)
    ,NmbrLivingUnits NUMERIC (1)
    ,SitusAddress CHAR (100)
    ,BuildingNumber CHAR (5)
    ,Fraction CHAR (3)
    ,DirectionPrefix CHAR (2)
    ,StreetName CHAR (25)
    ,StreetType CHAR (4)
    ,DirectionSuffix CHAR (2)
    ,ZipCode CHAR (10)
    ,Stories NUMERIC (3)
    ,BuildingGrade NUMERIC (2)
    ,BldgGradeVariation NUMERIC (2)
    ,SquareFtFstFlr NUMERIC (5)
    ,SquareFeetHalfFlr NUMERIC (5)
    ,SquareFeet2ndFlr NUMERIC (5)
    ,SquareFeetUpperFlr NUMERIC (5)
    ,SquareFeetUnfinishedFull NUMERIC (5)
    ,SquareFeetUnfinishedHalf NUMERIC (5)
    ,SquareFeetTotalLiving NUMERIC (5)
    ,SquareFeetTotalBasement NUMERIC (5)
    ,SquareFeetFinBasement NUMERIC (5)
    ,FinishedBasementGrade NUMERIC (2)
    ,SquareFeetGarageBasement NUMERIC (5)
    ,SquareFeetGarageAttached NUMERIC (5)
    ,DaylightBasement CHAR (1)
    ,SquareFeetOpenPorch NUMERIC (5)
    ,SquareFeetEnclosedPorch NUMERIC (5)
    ,SquareFeetDeck NUMERIC (6)
    ,HeatSystem NUMERIC (2)
    ,HeatSource NUMERIC (2)
    ,PercentBrickStone NUMERIC (3)
    ,ViewUtilization CHAR (1)
    ,Bedrooms NUMERIC (2)
    ,BathHalfCount NUMERIC (2)
    ,Bath3qtrCount NUMERIC (2)
    ,BathFullCount NUMERIC (2)
    ,FireplaceSingleStory NUMERIC (2)
    ,FireplaceMultipleStory NUMERIC (2)
    ,FireplaceFreeStanding NUMERIC (2)
    ,FireplaceAdditional NUMERIC (2)
    ,YearBuilt NUMERIC (4)
    ,YearRenovated NUMERIC (4)
    ,PercentComplete NUMERIC (3)
    ,Obsolescence NUMERIC (3)
    ,PercentNetCondition NUMERIC (3)
    ,Condition NUMERIC (1)
    ,AdditionalCost NUMERIC (10)
    );
 